program JieJieBox;

// All icons (named tray icons + MAINICON), VERSIONINFO and the application
// manifest live in app.res, generated by tools/make_app_res.py.
{$R 'app.res'}

uses
  Winapi.Windows,
  Winapi.Messages,
  System.SysUtils,
  Vcl.Forms,
  Main in 'Main.pas' {frmMain},
  SystemProxy in 'SystemProxy.pas',
  Drover in 'Drover.pas',
  Options in 'Options.pas',
  JsonUtils in 'JsonUtils.pas',
  CoreSupervisor in 'CoreSupervisor.pas',
  Logger in 'Logger.pas',
  AppArgs in 'AppArgs.pas',
  AppElevation in 'AppElevation.pas',
  AppSingleInstance in 'AppSingleInstance.pas',
  SingBoxConfig in 'SingBoxConfig.pas',
  CoreApiClient in 'CoreApiClient.pas',
  SingBoxBpf in 'SingBoxBpf.pas',
  ConfigReader in 'ConfigReader.pas',
  ConfigUpdater in 'ConfigUpdater.pas',
  ElevatedTrayIcon in 'ElevatedTrayIcon.pas',
  Autostart in 'Autostart.pas',
  SingBoxCli in 'SingBoxCli.pas',
  AppState in 'AppState.pas',
  SubscriptionManager in 'SubscriptionManager.pas',
  AppStrings in 'AppStrings.pas';

const
  APP_TITLE = AppStrings.APP_NAME_WINDOWS;

var
  Drover: TDrover;
  flags: TAppFlags;
  s: string;

begin
  try
    flags := GetAppFlags;

    if not AcquireSingleInstance('JieJieBox_SingleInstance_Mutex', afRestart in flags) then
      raise Exception.Create(AppStrings.DIALOG_SINGLE_INSTANCE);

    Drover := TDrover.Create(flags);
  except
    on E: Exception do
    begin
      s := E.Message;
      if s = '' then
        s := 'Unknown error.';

      MessageBox(0, PChar(AppStrings.DIALOG_FATAL_PREFIX + s), PChar(APP_TITLE), MB_ICONERROR);
      exit;
    end;
  end;

  // The config decides whether admin rights are needed: a `tun` inbound cannot
  // work without them. Ask for UAC once and restart elevated. If the user says
  // no, report it and exit - never silently fall back to a TUN-less run.
  if Drover.NeedsElevation then
  begin
    if AppElevation.LaunchSelf(FlagsToCmdLine([afTun, afRestart]), 0, true) then
    begin
      Drover.Free;
      exit;
    end;

    MessageBox(0, PChar(AppStrings.DIALOG_UAC_DECLINED), PChar(APP_TITLE), MB_ICONERROR);
    Drover.Free;
    exit;
  end;

  Drover.Start;

  Application.Initialize;
  Application.Title := AppStrings.APP_NAME;
  Application.MainFormOnTaskbar := false;
  Application.ShowMainForm := false;
  Application.CreateForm(TfrmMain, frmMain);
  frmMain.InitDrover(Drover);
  try
    Application.Run;
  finally
    FreeAndNil(Drover);
  end;

end.
